version: '3.8'

services:
  # Aplikacja CRM Next.js
  crm-app:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
       - NEXT_PUBLIC_SUPABASE_URL=https://pkhuggdkcglicghgxiyp.supabase.co
       - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraHVnZ2RrY2dsaWNnaGd4aXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTEwNzEsImV4cCI6MjA2NTQ4NzA3MX0.LbWtb-modRDlvnkGF5IswRHe1lJpd4zCMgkQ3_E0QQk
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://pkhuggdkcglicghgxiyp.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraHVnZ2RrY2dsaWNnaGd4aXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTEwNzEsImV4cCI6MjA2NTQ4NzA3MX0.LbWtb-modRDlvnkGF5IswRHe1lJpd4zCMgkQ3_E0QQk
    restart: unless-stopped
    networks:
      - crm-network
    # Opcjonalnie: mount volume dla plikow uploaded
    volumes:
      - app-uploads:/app/uploads

  # Nginx reverse proxy (opcjonalny)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Dla SSL certificates
    depends_on:
      - crm-app
    restart: unless-stopped
    networks:
      - crm-network
    profiles:
      - with-nginx  # Uruchom tylko gdy explicitly requested

volumes:
  app-uploads:
    driver: local

networks:
  crm-network:
    driver: bridge 